### ISSUE TITLE
Selecionar um dos casos de uso para ser implementado na SPRINT 1. Escrever os fluxos alternativos para o caso de uso selecionado.

### ISSUE THREAD

**Issue by tmsasaki** [Cassemiro1997/ppads-projeto-05j-2018s2#2]

**Comment by Cassemiro1997** [comment]
CDU002 - Cadastrar Doação

**Comment by tmsasaki** [comment]
Redigir os fluxos alternativos para o caso de uso "Cadastrar Doação".

**Comment by Cassemiro1997** [comment]
CDU002 - Cadastrar Doação
Ator Principal: Receptor

Resumo: Este caso de uso permite que o receptor possa cadastrar um local que necessita doação.

Fluxo principal
Funcionário seleciona a opção de cadastrar doação.
Sistema apresenta o formulário de preenchimento de doação.
Funcionário preenche o formulário.
Sistema valida a doação.

**Comment by Cassemiro1997** [comment]
CDU002 - Cadastrar Doação
Ator Principal: Receptor Resumo: Este caso de uso permite que o receptor possa cadastrar um local que necessita doação.

Fluxo principal
Funcionário seleciona a opção de cadastrar doação.
Sistema apresenta o formulário de preenchimento de doação.
Funcionário preenche o formulário.
Sistema valida a doação.
Ator seleciona a opção de cadastrar doação.
Sistema apresenta as opções com os tipos de itens para doação: vestuário, móveis e alimentos (FA1).
Sistema apresenta as opções de solicitar entrega (FA2) ou retirada pelo próprio receptor (FA3).
Ator confirma a solicitação.
Sistema valida a doação e encerra o caso de uso.
Fluxo Alternativo 1
Ator informa a quantidade e tipo de itens que necessitam de doação.
Sistema solicita confirmação do ator referente aos dados preenchidos.
Ator confirma ou edita a solicitação e retorna ao passo 3 do Fluxo Principal.
Fluxo Alternativo 2
Sistema apresenta formulário de preenchimento com o endereço de entrega da doação.
Ator preenche o formulário.
Sistema apresenta um aviso de confirmação da solicitação e retorna ao passo 4 do Fluxo Principal.
Fluxo Alternativo 3
Sistema apresenta formulário de preenchimento com os dados do receptor para efetuar a retirada da doação.
Ator preenche o formulário.
Sistema apresenta um aviso de confirmação da solicitação e retorna ao passo 4 do Fluxo Principal.

**Comment by Cassemiro1997** [comment]
## CDU002 - Cadastrar Doação
Ator Principal: Receptor
Resumo: Este caso de uso permite que o receptor possa cadastrar um local que necessita doação.

### Fluxo principal
1. Funcionário seleciona a opção de cadastrar doação.
2. Sistema apresenta o formulário de preenchimento de doação.
3. Funcionário preenche o formulário.
4. Sistema valida a doação.
5. Ator seleciona a opção de cadastrar doação.
6. Sistema apresenta as opções com os tipos de itens para doação: vestuário, móveis e alimentos (FA1).
7. Sistema apresenta as opções de solicitar entrega (FA2) ou retirada pelo próprio receptor (FA3).
8. Ator confirma a solicitação.
9. Sistema valida a doação e encerra o caso de uso.
#### Fluxo Alternativo 1
1. Ator informa a quantidade e tipo de itens que necessitam de doação.
2. Sistema solicita confirmação do ator referente aos dados preenchidos.
3. Ator confirma ou edita a solicitação e retorna ao passo 3 do Fluxo Principal.
#### Fluxo Alternativo 2
1. Sistema apresenta formulário de preenchimento com o endereço de entrega da doação.
2. Ator preenche o formulário.
3. Sistema apresenta um aviso de confirmação da solicitação e retorna ao passo 4 do Fluxo Principal.
#### Fluxo Alternativo 3
1. Sistema apresenta formulário de preenchimento com os dados do receptor para efetuar a retirada da doação.
2. Ator preenche o formulário.
3. Sistema apresenta um aviso de confirmação da solicitação e retorna ao passo 4 do Fluxo Principal.
