### ISSUE TITLE
Desenvolver e implantar uma aplicação Hello World na plataforma escolhida para o projeto. Postar URL no comentário até o dia 07/09.

### ISSUE THREAD

**Issue by tmsasaki** [Cassemiro1997/ppads-projeto-05j-2018s2#3]

**Comment by Cassemiro1997** [comment]
file:///C:/Temp/web/helloworld.html

**Comment by Cassemiro1997** [comment]
<!DOCTYPE html>
<html>
    
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Hello World</title>
    </head>
    <body>
         <h1>Hello World</h1>
    </body>
</html>

**Comment by Cassemiro1997** [comment]
https://ajudeummorador.000webhostapp.com/

**Comment by tmsasaki** [comment]
Ok.
